apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-rabbitmq-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "0"
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-rabbitmq-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "1"
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-rabbitmq-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rabbitmq
      podindex: "2"
  storageClassName: ""
